#pragma once

enum QUOTE_PRICE{
    FUTU_OPEN_PRICE,
    FUTU_HIGH_PRICE,
    FUTU_LOW_PRICE,
    FUTU_LAST_PRICE,
    AVERAGE_PRICE,
    UPLIMITED_PRICE,
    DOWNLIMITED_PRICE,

    FUTU_CLOSE_PRICE,
    PRE_CLOSE_PRICE,
    SQUARE_PRICE,
    PRE_SQUARE_PRICE,
    BUSINESS_BALANCE,

    BID_PRICE1,
    BID_PRICE2,
    BID_PRICE3,
    BID_PRICE4,
    BID_PRICE5,

    ASK_PRICE1,
    ASK_PRICE2,
    ASK_PRICE3,
    ASK_PRICE4,
    ASK_PRICE5,

    FORM_BID_PRICE,
    FORM_ASK_PRICE
};

enum QUOTE_QUANTITY{
    BUSINESS_VOLUME,
    OPEN_INTEREST,
    PRE_OPEN_INTEREST,

    BID_TOTAL_VOLUME,
    BID_VOLUME1,
    BID_VOLUME2,
    BID_VOLUME3,
    BID_VOLUME4,
    BID_VOLUME5,

    ASK_TOTAL_VOLUME,
    ASK_VOLUME1,
    ASK_VOLUME2,
    ASK_VOLUME3,
    ASK_VOLUME4,
    ASK_VOLUME5,

    FORM_BID_VOLUME,
    FORM_ASK_VOLUME,

};

enum QUOTE_INDEX{
    PRE_DELTA,
    CURR_DELTA

};